[master]
13.201.64.148 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/Nov-jenkins.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[workers]
65.2.187.148 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/Nov-jenkins.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
52.66.6.61 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/Nov-jenkins.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[jenkins]
65.0.81.249 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/Nov-jenkins.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[k8s:children]
master
workers
