{{- if gt (int .Values.database.replicas) 1 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.replicaServiceName }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.targetPort }}
  selector:
    module: db-postgres
    role: replica
{{- end }}
