apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.headlessServiceName }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.targetPort }}
  selector:
    module: db-postgres
